services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mlx.address=:11432"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--tracing.enabled=true"
      - "--accesslog=true"
      - "--log.level=DEBUG"
      # Add detailed logging configuration
      - "--log.format=json"
      - "--accesslog.format=json"
      - "--accesslog.fields.headers.names.X-Request-ID=keep"
      - "--accesslog.fields.headers.names.X-Real-IP=keep"
      - "--providers.docker.watch=true"
      - "--providers.docker.network=litellm-public"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "traefik-logs"
        env: "os,customer"
        tag: "{{.Name}}/{{.ID}}"
    ports:
      - "80:80"
      - "443:443" 
      - "11432:11432"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/etc/traefik
      - ./traefik/certificates:/certificates
      - ${LETSENCRYPT_DATA_DIR:-./traefik/letsencrypt}:/letsencrypt
    networks:
      - litellm-public
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${TRAEFIK_HOSTNAME:-traefik.localhost.loc}`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      # Metrics endpoint
      - "traefik.http.routers.traefik-metrics.rule=Host(`${TRAEFIK_HOSTNAME:-traefik.localhost.loc}`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.traefik-metrics.service=prometheus@internal"
      - "traefik.http.routers.traefik-metrics.entrypoints=web"
      # Health checks
      - "traefik.http.routers.traefik-health.rule=Host(`${TRAEFIK_HOSTNAME:-traefik.localhost.loc}`) && PathPrefix(`/health`)"
      - "traefik.http.routers.traefik-health.service=ping@internal"
      - "traefik.http.routers.traefik-health.entrypoints=web"
      # Traces
      - "traefik.http.routers.traefik-traces.rule=Host(`${TRAEFIK_HOSTNAME:-traefik.localhost.loc}`) && PathPrefix(`/traces`)"
      - "traefik.http.routers.traefik-traces.entrypoints=web"
      # MLX-LM Service running on HOST
      - "traefik.http.routers.mlx.rule=Host(`mlx.localhost.loc`)"
      - "traefik.http.routers.mlx.entrypoints=web,websecure"
      - "traefik.http.routers.mlx.tls=true"
      - "traefik.http.routers.mlx.tls.certresolver=letsencrypt"
      - "traefik.http.services.mlx.loadbalancer.server.url=http://host.docker.internal:11432"

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    volumes:
      - ./litellm:/litellm
    environment:
      - PORT=${LITELLM_PORT:-11400}
      - HOST=0.0.0.0
      - CONFIG_PATH=/litellm/config.yaml
      - LOG_LEVEL=DEBUG  # Add explicit log level
      - DEBUG=1  # Enable debug mode
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "litellm-logs"
        env: "os,customer"
        tag: "{{.Name}}/{{.ID}}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${LITELLM_PORT:-11400}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      # HTTP endpoint
      - "traefik.http.routers.litellm-http.rule=Host(`${LITELLM_HTTP_HOSTNAME:-litellm.localhost.loc}`)"
      - "traefik.http.routers.litellm-http.entrypoints=web"
      - "traefik.http.services.litellm-http.loadbalancer.server.port=${LITELLM_PORT:-11400}"
      # HTTPS endpoint with TLS offloading
      - "traefik.http.routers.litellm-https.rule=Host(`${LITELLM_HTTP_HOSTNAME:-litellm.localhost.loc}`)" 
      - "traefik.http.routers.litellm-https.entrypoints=websecure"
      - "traefik.http.routers.litellm-https.tls=${AUTO_SSL:-false}"
      - "traefik.http.routers.litellm-https.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
networks:
  litellm-public:
    name: litellm-public

# Add logging configuration for docker-compose
x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
    labels: "docker-compose-logs"
volumes:
  hf_cache:
    driver: local