http:
  middlewares:
    # Security middleware
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    
    # CORS middleware
    cors:
      headers:
        accessControlAllowMethods: "GET,OPTIONS,PUT,POST,DELETE"
        accessControlAllowHeaders: "*"
        accessControlAllowOrigin: "*"

    # Rate limiting middleware
    rateLimiter:
      rateLimit:
        average: 100
        burst: 50
        period: 1m

  # Specify services manually if needed
  services:
    mlx-api:
      loadBalancer:
        servers:
          - url: "http://mlx-lm:11432"

    litellm-api:
      loadBalancer:
        servers:
          - url: "http://litellm:11400"

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"