entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: "litellm-public"
  file:
    directory: "/etc/traefik/config"
    watch: true

log:
  level: "DEBUG"
  format: "json"

accessLog: 
  format: "json"
  bufferingSize: 100
  filePath: "/dev/stdout"
  fields:
    headers:
      names:
        X-Request-ID: keep
        X-Real-IP: keep


# tracing:
#   serviceName: "traefik"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.0
      - 2.0
      - 5.0
      - 10.0

ping:
  entryPoint: "web"
  manualRouting: true

tls:
  certificates:
    - certFile: "/etc/traefik/certificates/anthropic/api.anthropic.com.crt"
      keyFile: "/etc/traefik/certificates/anthropic/api.anthropic.com.key"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certificates/cert.pem"
        keyFile: "/etc/traefik/certificates/key.pem"

certificatesResolvers:
  selfsigned:
    acme:
      caServer: "internal"
      storage: "/etc/traefik/certificates/acme.json"
      keyType: "EC256"